// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package assignment;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface clockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:clock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional int32 clock = 2;</code>
     */
    int getClock();
  }
  /**
   * Protobuf type {@code clock}
   */
  public  static final class clock extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:clock)
      clockOrBuilder {
    // Use clock.newBuilder() to construct.
    private clock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private clock() {
      id_ = 0;
      clock_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private clock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              clock_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return assignment.MessageProto.internal_static_clock_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return assignment.MessageProto.internal_static_clock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              assignment.MessageProto.clock.class, assignment.MessageProto.clock.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int CLOCK_FIELD_NUMBER = 2;
    private int clock_;
    /**
     * <code>optional int32 clock = 2;</code>
     */
    public int getClock() {
      return clock_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (clock_ != 0) {
        output.writeInt32(2, clock_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (clock_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, clock_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof assignment.MessageProto.clock)) {
        return super.equals(obj);
      }
      assignment.MessageProto.clock other = (assignment.MessageProto.clock) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getClock()
          == other.getClock());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + CLOCK_FIELD_NUMBER;
      hash = (53 * hash) + getClock();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static assignment.MessageProto.clock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static assignment.MessageProto.clock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static assignment.MessageProto.clock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static assignment.MessageProto.clock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static assignment.MessageProto.clock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static assignment.MessageProto.clock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static assignment.MessageProto.clock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static assignment.MessageProto.clock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static assignment.MessageProto.clock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static assignment.MessageProto.clock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(assignment.MessageProto.clock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code clock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:clock)
        assignment.MessageProto.clockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return assignment.MessageProto.internal_static_clock_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return assignment.MessageProto.internal_static_clock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                assignment.MessageProto.clock.class, assignment.MessageProto.clock.Builder.class);
      }

      // Construct using assignment.MessageProto.clock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        clock_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return assignment.MessageProto.internal_static_clock_descriptor;
      }

      public assignment.MessageProto.clock getDefaultInstanceForType() {
        return assignment.MessageProto.clock.getDefaultInstance();
      }

      public assignment.MessageProto.clock build() {
        assignment.MessageProto.clock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public assignment.MessageProto.clock buildPartial() {
        assignment.MessageProto.clock result = new assignment.MessageProto.clock(this);
        result.id_ = id_;
        result.clock_ = clock_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof assignment.MessageProto.clock) {
          return mergeFrom((assignment.MessageProto.clock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(assignment.MessageProto.clock other) {
        if (other == assignment.MessageProto.clock.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getClock() != 0) {
          setClock(other.getClock());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        assignment.MessageProto.clock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (assignment.MessageProto.clock) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int clock_ ;
      /**
       * <code>optional int32 clock = 2;</code>
       */
      public int getClock() {
        return clock_;
      }
      /**
       * <code>optional int32 clock = 2;</code>
       */
      public Builder setClock(int value) {
        
        clock_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clock = 2;</code>
       */
      public Builder clearClock() {
        
        clock_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:clock)
    }

    // @@protoc_insertion_point(class_scope:clock)
    private static final assignment.MessageProto.clock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new assignment.MessageProto.clock();
    }

    public static assignment.MessageProto.clock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<clock>
        PARSER = new com.google.protobuf.AbstractParser<clock>() {
      public clock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new clock(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<clock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<clock> getParserForType() {
      return PARSER;
    }

    public assignment.MessageProto.clock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface generalisedClockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:generalisedClock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .clock clocks = 1;</code>
     */
    java.util.List<assignment.MessageProto.clock> 
        getClocksList();
    /**
     * <code>repeated .clock clocks = 1;</code>
     */
    assignment.MessageProto.clock getClocks(int index);
    /**
     * <code>repeated .clock clocks = 1;</code>
     */
    int getClocksCount();
    /**
     * <code>repeated .clock clocks = 1;</code>
     */
    java.util.List<? extends assignment.MessageProto.clockOrBuilder> 
        getClocksOrBuilderList();
    /**
     * <code>repeated .clock clocks = 1;</code>
     */
    assignment.MessageProto.clockOrBuilder getClocksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code generalisedClock}
   */
  public  static final class generalisedClock extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:generalisedClock)
      generalisedClockOrBuilder {
    // Use generalisedClock.newBuilder() to construct.
    private generalisedClock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private generalisedClock() {
      clocks_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private generalisedClock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                clocks_ = new java.util.ArrayList<assignment.MessageProto.clock>();
                mutable_bitField0_ |= 0x00000001;
              }
              clocks_.add(
                  input.readMessage(assignment.MessageProto.clock.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          clocks_ = java.util.Collections.unmodifiableList(clocks_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return assignment.MessageProto.internal_static_generalisedClock_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return assignment.MessageProto.internal_static_generalisedClock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              assignment.MessageProto.generalisedClock.class, assignment.MessageProto.generalisedClock.Builder.class);
    }

    public static final int CLOCKS_FIELD_NUMBER = 1;
    private java.util.List<assignment.MessageProto.clock> clocks_;
    /**
     * <code>repeated .clock clocks = 1;</code>
     */
    public java.util.List<assignment.MessageProto.clock> getClocksList() {
      return clocks_;
    }
    /**
     * <code>repeated .clock clocks = 1;</code>
     */
    public java.util.List<? extends assignment.MessageProto.clockOrBuilder> 
        getClocksOrBuilderList() {
      return clocks_;
    }
    /**
     * <code>repeated .clock clocks = 1;</code>
     */
    public int getClocksCount() {
      return clocks_.size();
    }
    /**
     * <code>repeated .clock clocks = 1;</code>
     */
    public assignment.MessageProto.clock getClocks(int index) {
      return clocks_.get(index);
    }
    /**
     * <code>repeated .clock clocks = 1;</code>
     */
    public assignment.MessageProto.clockOrBuilder getClocksOrBuilder(
        int index) {
      return clocks_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < clocks_.size(); i++) {
        output.writeMessage(1, clocks_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < clocks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, clocks_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof assignment.MessageProto.generalisedClock)) {
        return super.equals(obj);
      }
      assignment.MessageProto.generalisedClock other = (assignment.MessageProto.generalisedClock) obj;

      boolean result = true;
      result = result && getClocksList()
          .equals(other.getClocksList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getClocksCount() > 0) {
        hash = (37 * hash) + CLOCKS_FIELD_NUMBER;
        hash = (53 * hash) + getClocksList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static assignment.MessageProto.generalisedClock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static assignment.MessageProto.generalisedClock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static assignment.MessageProto.generalisedClock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static assignment.MessageProto.generalisedClock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static assignment.MessageProto.generalisedClock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static assignment.MessageProto.generalisedClock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static assignment.MessageProto.generalisedClock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static assignment.MessageProto.generalisedClock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static assignment.MessageProto.generalisedClock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static assignment.MessageProto.generalisedClock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(assignment.MessageProto.generalisedClock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code generalisedClock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:generalisedClock)
        assignment.MessageProto.generalisedClockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return assignment.MessageProto.internal_static_generalisedClock_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return assignment.MessageProto.internal_static_generalisedClock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                assignment.MessageProto.generalisedClock.class, assignment.MessageProto.generalisedClock.Builder.class);
      }

      // Construct using assignment.MessageProto.generalisedClock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getClocksFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (clocksBuilder_ == null) {
          clocks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          clocksBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return assignment.MessageProto.internal_static_generalisedClock_descriptor;
      }

      public assignment.MessageProto.generalisedClock getDefaultInstanceForType() {
        return assignment.MessageProto.generalisedClock.getDefaultInstance();
      }

      public assignment.MessageProto.generalisedClock build() {
        assignment.MessageProto.generalisedClock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public assignment.MessageProto.generalisedClock buildPartial() {
        assignment.MessageProto.generalisedClock result = new assignment.MessageProto.generalisedClock(this);
        int from_bitField0_ = bitField0_;
        if (clocksBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            clocks_ = java.util.Collections.unmodifiableList(clocks_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.clocks_ = clocks_;
        } else {
          result.clocks_ = clocksBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof assignment.MessageProto.generalisedClock) {
          return mergeFrom((assignment.MessageProto.generalisedClock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(assignment.MessageProto.generalisedClock other) {
        if (other == assignment.MessageProto.generalisedClock.getDefaultInstance()) return this;
        if (clocksBuilder_ == null) {
          if (!other.clocks_.isEmpty()) {
            if (clocks_.isEmpty()) {
              clocks_ = other.clocks_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureClocksIsMutable();
              clocks_.addAll(other.clocks_);
            }
            onChanged();
          }
        } else {
          if (!other.clocks_.isEmpty()) {
            if (clocksBuilder_.isEmpty()) {
              clocksBuilder_.dispose();
              clocksBuilder_ = null;
              clocks_ = other.clocks_;
              bitField0_ = (bitField0_ & ~0x00000001);
              clocksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getClocksFieldBuilder() : null;
            } else {
              clocksBuilder_.addAllMessages(other.clocks_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        assignment.MessageProto.generalisedClock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (assignment.MessageProto.generalisedClock) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<assignment.MessageProto.clock> clocks_ =
        java.util.Collections.emptyList();
      private void ensureClocksIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          clocks_ = new java.util.ArrayList<assignment.MessageProto.clock>(clocks_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          assignment.MessageProto.clock, assignment.MessageProto.clock.Builder, assignment.MessageProto.clockOrBuilder> clocksBuilder_;

      /**
       * <code>repeated .clock clocks = 1;</code>
       */
      public java.util.List<assignment.MessageProto.clock> getClocksList() {
        if (clocksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(clocks_);
        } else {
          return clocksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .clock clocks = 1;</code>
       */
      public int getClocksCount() {
        if (clocksBuilder_ == null) {
          return clocks_.size();
        } else {
          return clocksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .clock clocks = 1;</code>
       */
      public assignment.MessageProto.clock getClocks(int index) {
        if (clocksBuilder_ == null) {
          return clocks_.get(index);
        } else {
          return clocksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .clock clocks = 1;</code>
       */
      public Builder setClocks(
          int index, assignment.MessageProto.clock value) {
        if (clocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClocksIsMutable();
          clocks_.set(index, value);
          onChanged();
        } else {
          clocksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .clock clocks = 1;</code>
       */
      public Builder setClocks(
          int index, assignment.MessageProto.clock.Builder builderForValue) {
        if (clocksBuilder_ == null) {
          ensureClocksIsMutable();
          clocks_.set(index, builderForValue.build());
          onChanged();
        } else {
          clocksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .clock clocks = 1;</code>
       */
      public Builder addClocks(assignment.MessageProto.clock value) {
        if (clocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClocksIsMutable();
          clocks_.add(value);
          onChanged();
        } else {
          clocksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .clock clocks = 1;</code>
       */
      public Builder addClocks(
          int index, assignment.MessageProto.clock value) {
        if (clocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClocksIsMutable();
          clocks_.add(index, value);
          onChanged();
        } else {
          clocksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .clock clocks = 1;</code>
       */
      public Builder addClocks(
          assignment.MessageProto.clock.Builder builderForValue) {
        if (clocksBuilder_ == null) {
          ensureClocksIsMutable();
          clocks_.add(builderForValue.build());
          onChanged();
        } else {
          clocksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .clock clocks = 1;</code>
       */
      public Builder addClocks(
          int index, assignment.MessageProto.clock.Builder builderForValue) {
        if (clocksBuilder_ == null) {
          ensureClocksIsMutable();
          clocks_.add(index, builderForValue.build());
          onChanged();
        } else {
          clocksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .clock clocks = 1;</code>
       */
      public Builder addAllClocks(
          java.lang.Iterable<? extends assignment.MessageProto.clock> values) {
        if (clocksBuilder_ == null) {
          ensureClocksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, clocks_);
          onChanged();
        } else {
          clocksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .clock clocks = 1;</code>
       */
      public Builder clearClocks() {
        if (clocksBuilder_ == null) {
          clocks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          clocksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .clock clocks = 1;</code>
       */
      public Builder removeClocks(int index) {
        if (clocksBuilder_ == null) {
          ensureClocksIsMutable();
          clocks_.remove(index);
          onChanged();
        } else {
          clocksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .clock clocks = 1;</code>
       */
      public assignment.MessageProto.clock.Builder getClocksBuilder(
          int index) {
        return getClocksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .clock clocks = 1;</code>
       */
      public assignment.MessageProto.clockOrBuilder getClocksOrBuilder(
          int index) {
        if (clocksBuilder_ == null) {
          return clocks_.get(index);  } else {
          return clocksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .clock clocks = 1;</code>
       */
      public java.util.List<? extends assignment.MessageProto.clockOrBuilder> 
           getClocksOrBuilderList() {
        if (clocksBuilder_ != null) {
          return clocksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(clocks_);
        }
      }
      /**
       * <code>repeated .clock clocks = 1;</code>
       */
      public assignment.MessageProto.clock.Builder addClocksBuilder() {
        return getClocksFieldBuilder().addBuilder(
            assignment.MessageProto.clock.getDefaultInstance());
      }
      /**
       * <code>repeated .clock clocks = 1;</code>
       */
      public assignment.MessageProto.clock.Builder addClocksBuilder(
          int index) {
        return getClocksFieldBuilder().addBuilder(
            index, assignment.MessageProto.clock.getDefaultInstance());
      }
      /**
       * <code>repeated .clock clocks = 1;</code>
       */
      public java.util.List<assignment.MessageProto.clock.Builder> 
           getClocksBuilderList() {
        return getClocksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          assignment.MessageProto.clock, assignment.MessageProto.clock.Builder, assignment.MessageProto.clockOrBuilder> 
          getClocksFieldBuilder() {
        if (clocksBuilder_ == null) {
          clocksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              assignment.MessageProto.clock, assignment.MessageProto.clock.Builder, assignment.MessageProto.clockOrBuilder>(
                  clocks_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          clocks_ = null;
        }
        return clocksBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:generalisedClock)
    }

    // @@protoc_insertion_point(class_scope:generalisedClock)
    private static final assignment.MessageProto.generalisedClock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new assignment.MessageProto.generalisedClock();
    }

    public static assignment.MessageProto.generalisedClock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<generalisedClock>
        PARSER = new com.google.protobuf.AbstractParser<generalisedClock>() {
      public generalisedClock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new generalisedClock(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<generalisedClock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<generalisedClock> getParserForType() {
      return PARSER;
    }

    public assignment.MessageProto.generalisedClock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional .generalisedClock clock = 2;</code>
     */
    boolean hasClock();
    /**
     * <code>optional .generalisedClock clock = 2;</code>
     */
    assignment.MessageProto.generalisedClock getClock();
    /**
     * <code>optional .generalisedClock clock = 2;</code>
     */
    assignment.MessageProto.generalisedClockOrBuilder getClockOrBuilder();
  }
  /**
   * Protobuf type {@code Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      id_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              assignment.MessageProto.generalisedClock.Builder subBuilder = null;
              if (clock_ != null) {
                subBuilder = clock_.toBuilder();
              }
              clock_ = input.readMessage(assignment.MessageProto.generalisedClock.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(clock_);
                clock_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return assignment.MessageProto.internal_static_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return assignment.MessageProto.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              assignment.MessageProto.Message.class, assignment.MessageProto.Message.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int CLOCK_FIELD_NUMBER = 2;
    private assignment.MessageProto.generalisedClock clock_;
    /**
     * <code>optional .generalisedClock clock = 2;</code>
     */
    public boolean hasClock() {
      return clock_ != null;
    }
    /**
     * <code>optional .generalisedClock clock = 2;</code>
     */
    public assignment.MessageProto.generalisedClock getClock() {
      return clock_ == null ? assignment.MessageProto.generalisedClock.getDefaultInstance() : clock_;
    }
    /**
     * <code>optional .generalisedClock clock = 2;</code>
     */
    public assignment.MessageProto.generalisedClockOrBuilder getClockOrBuilder() {
      return getClock();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (clock_ != null) {
        output.writeMessage(2, getClock());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (clock_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getClock());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof assignment.MessageProto.Message)) {
        return super.equals(obj);
      }
      assignment.MessageProto.Message other = (assignment.MessageProto.Message) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (hasClock() == other.hasClock());
      if (hasClock()) {
        result = result && getClock()
            .equals(other.getClock());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      if (hasClock()) {
        hash = (37 * hash) + CLOCK_FIELD_NUMBER;
        hash = (53 * hash) + getClock().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static assignment.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static assignment.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static assignment.MessageProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static assignment.MessageProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static assignment.MessageProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static assignment.MessageProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static assignment.MessageProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static assignment.MessageProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static assignment.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static assignment.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(assignment.MessageProto.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        assignment.MessageProto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return assignment.MessageProto.internal_static_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return assignment.MessageProto.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                assignment.MessageProto.Message.class, assignment.MessageProto.Message.Builder.class);
      }

      // Construct using assignment.MessageProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        if (clockBuilder_ == null) {
          clock_ = null;
        } else {
          clock_ = null;
          clockBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return assignment.MessageProto.internal_static_Message_descriptor;
      }

      public assignment.MessageProto.Message getDefaultInstanceForType() {
        return assignment.MessageProto.Message.getDefaultInstance();
      }

      public assignment.MessageProto.Message build() {
        assignment.MessageProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public assignment.MessageProto.Message buildPartial() {
        assignment.MessageProto.Message result = new assignment.MessageProto.Message(this);
        result.id_ = id_;
        if (clockBuilder_ == null) {
          result.clock_ = clock_;
        } else {
          result.clock_ = clockBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof assignment.MessageProto.Message) {
          return mergeFrom((assignment.MessageProto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(assignment.MessageProto.Message other) {
        if (other == assignment.MessageProto.Message.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.hasClock()) {
          mergeClock(other.getClock());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        assignment.MessageProto.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (assignment.MessageProto.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private assignment.MessageProto.generalisedClock clock_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          assignment.MessageProto.generalisedClock, assignment.MessageProto.generalisedClock.Builder, assignment.MessageProto.generalisedClockOrBuilder> clockBuilder_;
      /**
       * <code>optional .generalisedClock clock = 2;</code>
       */
      public boolean hasClock() {
        return clockBuilder_ != null || clock_ != null;
      }
      /**
       * <code>optional .generalisedClock clock = 2;</code>
       */
      public assignment.MessageProto.generalisedClock getClock() {
        if (clockBuilder_ == null) {
          return clock_ == null ? assignment.MessageProto.generalisedClock.getDefaultInstance() : clock_;
        } else {
          return clockBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .generalisedClock clock = 2;</code>
       */
      public Builder setClock(assignment.MessageProto.generalisedClock value) {
        if (clockBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          clock_ = value;
          onChanged();
        } else {
          clockBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .generalisedClock clock = 2;</code>
       */
      public Builder setClock(
          assignment.MessageProto.generalisedClock.Builder builderForValue) {
        if (clockBuilder_ == null) {
          clock_ = builderForValue.build();
          onChanged();
        } else {
          clockBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .generalisedClock clock = 2;</code>
       */
      public Builder mergeClock(assignment.MessageProto.generalisedClock value) {
        if (clockBuilder_ == null) {
          if (clock_ != null) {
            clock_ =
              assignment.MessageProto.generalisedClock.newBuilder(clock_).mergeFrom(value).buildPartial();
          } else {
            clock_ = value;
          }
          onChanged();
        } else {
          clockBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .generalisedClock clock = 2;</code>
       */
      public Builder clearClock() {
        if (clockBuilder_ == null) {
          clock_ = null;
          onChanged();
        } else {
          clock_ = null;
          clockBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .generalisedClock clock = 2;</code>
       */
      public assignment.MessageProto.generalisedClock.Builder getClockBuilder() {
        
        onChanged();
        return getClockFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .generalisedClock clock = 2;</code>
       */
      public assignment.MessageProto.generalisedClockOrBuilder getClockOrBuilder() {
        if (clockBuilder_ != null) {
          return clockBuilder_.getMessageOrBuilder();
        } else {
          return clock_ == null ?
              assignment.MessageProto.generalisedClock.getDefaultInstance() : clock_;
        }
      }
      /**
       * <code>optional .generalisedClock clock = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          assignment.MessageProto.generalisedClock, assignment.MessageProto.generalisedClock.Builder, assignment.MessageProto.generalisedClockOrBuilder> 
          getClockFieldBuilder() {
        if (clockBuilder_ == null) {
          clockBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              assignment.MessageProto.generalisedClock, assignment.MessageProto.generalisedClock.Builder, assignment.MessageProto.generalisedClockOrBuilder>(
                  getClock(),
                  getParentForChildren(),
                  isClean());
          clock_ = null;
        }
        return clockBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final assignment.MessageProto.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new assignment.MessageProto.Message();
    }

    public static assignment.MessageProto.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public assignment.MessageProto.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clock_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generalisedClock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generalisedClock_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\"\"\n\005clock\022\n\n\002id\030\001 \001(\005\022\r\n\005" +
      "clock\030\002 \001(\005\"*\n\020generalisedClock\022\026\n\006clock" +
      "s\030\001 \003(\0132\006.clock\"7\n\007Message\022\n\n\002id\030\001 \001(\005\022 " +
      "\n\005clock\030\002 \001(\0132\021.generalisedClockB\032\n\nassi" +
      "gnmentB\014MessageProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_clock_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_clock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clock_descriptor,
        new java.lang.String[] { "Id", "Clock", });
    internal_static_generalisedClock_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_generalisedClock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generalisedClock_descriptor,
        new java.lang.String[] { "Clocks", });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Id", "Clock", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
